# Generated by Django 4.2.20 on 2025-05-10 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nep_app', '0049_advertisement_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='ad/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', max_length=200)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItemModel',
        ),
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartModel',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='header',
            new_name='HeaderModel',
        ),
        migrations.RenameModel(
            old_name='image_Slider',
            new_name='image_SliderModel',
        ),
        migrations.RenameModel(
            old_name='OtherDetail',
            new_name='OtherDetailModel',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='Sub_CategoryModel',
        ),
        migrations.DeleteModel(
            name='advertisement',
        ),
    ]
