# Generated by Django 4.2.20 on 2025-05-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0050_advertisementmodel_socialmediamodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of the price at the time the item was added', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='nep_app.productmodel'),
        ),
    ]
