# Generated by Django 4.2.20 on 2025-05-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0052_order_shippinginfomodel_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
